(define(problem robot-cup-problem)
(:domain robot-cup-domain)
(:objects pos1 pos2 pos3 pos4 cupR cupY cupB)
(:init (pos pos1)
       (pos pos2)
       (pos pos3)
       (pos pos4)
       (cup cupR)
       (cup cupY)
       (cup cupB)
       (at cupY pos1)
       (empty pos2)
       (at cupR pos3)
       (at cupB pos4)
)
(:goal (and (at cupR pos1)(at cupY pos2)(at cupB pos3)(empty pos4)  ))
)
